---
all:
  vars:
    repo_url: https://github.com/enriqTS/homelab.git
    repo_branch: main
    repo_path: /opt/homelab
  children:
    pihole:
      hosts:
        raspberrypi:
          ansible_host: 192.168.1.10
          ansible_user: pi
      vars:
        deploy_stacks:
          - pi-hole
    minipc:
      hosts:
        notebook:
          ansible_host: 10.0.0.129
          ansible_user: henrique
          ansible_connection: local
      vars:
        deploy_stacks:
          - nginx-proxy
          - grafana-stack
          - homepage
          - portainer
          - searxng
          - perplexica
    desktop:
      hosts:
        desktop_host:
          ansible_host: 192.168.1.30
          ansible_user: henrique
      vars:
        install_nvidia_toolkit: true
        deploy_stacks:
          - llm-stack/ollama
          - llm-stack/open-webui
        ollama_models:
          - qwen3.8
          - gemma4:e2b
          - lfm2.5
